
export const CATEGOTY_ACTION_TYPE = {
  SET_CATEGORIES:"category/SET_CATEGORIES",
  FETCH_CATEGORIES_START:"category/FETCH_CATEGORIES_",
  FETCH_CATEGORIES_SUCCESS:"category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED:"category/FETCH_CATEGORIES_FAILED",
}